config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :items, except: :index
  end

  root 'lists#index' # ListsController

  namespace :api, constraints: lambda { |req| req.format == :json } do
    namespace :v1 do
      resources :users
      resources :lists, except: [:new, :edit] do
        resources :items, except: [:new, :edit]
      end

      post '/login' => 'sessions#create'
      delete '/logout' => 'sessions#destroy'
    end
  end

  match '*path', via: [:options], to:  lambda {|_| [204, {'Content-Type' => 'text/plain'}, []]}

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items, dependent: :destroy

  validates :name, length: {minimum: 3}
  validates :name, uniqueness: true
end

app/controllers/api/v1/lists_controller.rb
class Api::V1::ListsController < ApiController
  before_action :find_list, only: [:show, :update, :destroy]
  before_action :ensure_authenticated, only: [:create, :update, :destroy]

  # GET /api/v1/lists
  def index
    @lists = List.all
    render json: @lists
  end

  # GET /api/v1/lists/:id
  def show
    render json: @list
  end

  # POST /api/v1/lists
  def create
    @list = List.new(list_params)

    if @list.save
      render json: @list
    else
      render json: @list.errors, status: :unprocessable_entity
    end
  end

  # PUT /api/v1/lists/:id
  def update
    if @list.update(list_params)
      # if the update succeeds
      render json: @list
    else
      render json: @list.errors, status: :unprocessable_entity
    end
  end

  # DELETE /api/v1/lists/:id
  def destroy
    @list.destroy
    render json: { success: true }
  end

  private
  def ensure_authenticated
    render json: { message: 'You are not authorized to do that.'}, status: :unauthorized unless current_user
  end

  def list_params
    params.require(:list).permit(:name)
  end

  def find_list
    @list = List.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show, :edit, :update, :destroy]

  # GET /lists, all lists
  def index
    @lists = List.all.reverse_order.page(params[:page])

    # for the modal to create list
    @list = List.new
  end

  # GET /lists/:id, single list
  def show
    @items = @list.items.reverse_order.page(params[:page])
    @item = Item.new
  end

  # GET /lists/new, to show form that will be used for creating a list
  def new
    @list = List.new
  end

  # POST /lists, endpoint to insert list into db
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        # if @list.save succeeds
        format.html { redirect_to(lists_path, notice: "List #{@list.name} was successfully created!") }
        format.js {}
      else
        # if @list.save fails
        format.html { render('new', alert: "Something went wrong!") }
        format.js {}
      end
    end
  end

  # GET /lists/:id/edit, to show the form that will be used for editing list with id == :id
  def edit
  end

  # PUT /lists/:id, to update the list with id == :id
  def update
    if @list.update(list_params)
      # if the update succeeds
      flash[:notice] = "List #{@list.name} was successfully updated!"
      redirect_to(@list)
    else
      # if the update fails
      flash[:alert] = "Something went wrong!"
      render('edit')
    end
  end

  # DELETE /lists/:id, to destroy a list with id == :id
  def destroy
    @list.destroy

    flash[:notice] = "List destroyed!"
    redirect_to(root_path)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def find_list
    @list = List.find(params[:id])
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<% if list.errors.any? %>
  <%= render partial: "list_errors", locals: {list: @list}%>
<% end %>

<%= form_for list, url: {action: action}, remote: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, id: "list-name-input" %>

  <%= form.submit "#{action.capitalize} List", class: "btn btn-primary" %>
<% end %>

app/views/lists/_list.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="list">
      <ul class="item-right">
        <li><%= button_to "Edit List", edit_list_path(list), method: "get" %></li>
        <li><%= button_to "Delete List", list, method: "delete" %></li>
      </ul>

      <%= link_to list.name, list %>
    </div>
  </div>
</div>

app/views/lists/_list_errors.html.erb
<div id="error_explanation">
  <h2><%= pluralize(list.errors.count, "error") %> prohibited this article from being saved.</h2>

  <ul>
    <% list.errors.full_messages.each do |error_message| %>
    <li><%= error_message %></li>
    <% end %>
  </ul>
</div>

app/views/lists/create.js.erb
<% if @list.errors.any? %>
  $("#list-errors").html("<%= escape_javascript(render partial: 'list_errors', locals: {list: @list}) %>");
<% else%>
  $("#list-errors").html("");
  var listElement = $(".list");
  if (listElement.length >= 5) {
    $(".list").last().remove();
  }
  if (listElement.length >= 5 && isLastPage()) {
    addNewPage("/lists");
  }
  $("#lists").prepend("<%= escape_javascript(render @list) %>");
  $("#create-list-modal").modal("hide");
  $("#list-name-input").val("");
  // window.location = "/lists";
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List: <%= @list.name %></h1>

<%= render partial: "form",locals: {list: @list, action: "update"}%>

app/views/lists/index.html.erb
<div id="lists">
  <%= render @lists %>
</div>
<div class="row pagination-links">
  <%= paginate @lists %>
</div>
<!-- Modal -->
<div class="modal fade" id="create-list-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="create-list-label">Create a new List</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "form", locals: {list: @list, action: "create"} %>
        <div id='list-errors'></div>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create New List</h1>

<%= render partial: "form", locals: {list: @list, action: "create"} %>

app/views/lists/show.html.erb
<%= content_for(:list_name, @list.name) %>
<%= content_for(:new_path, new_list_item_path(@list)) %>

<div id="items">
  <%= render @items %>
</div>
<div class="row pagination-links">
  <%= paginate @items %>
</div>
<!--
<%= button_to "Edit List", edit_list_path(@list), method: "get" %>
<%= button_to "Delete List", @list, method: "delete" %>
-->

<!-- Modal -->
<div class="modal fade" id="create-item-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="create-item-label">Create a new Item</h4>
      </div>
      <div class="modal-body">
        <%= render partial: "items/create_form", locals: {list: @list, item: @item} %>
        <div id='item-errors'></div>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>