config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :items, except: :index
  end

  root 'lists#index' # ListsController

  namespace :api, constraints: lambda { |req| req.format == :json } do
    namespace :v1 do
      resources :users
      resources :lists, except: [:new, :edit] do
        resources :items, except: [:new, :edit]
      end

      post '/login' => 'sessions#create'
      delete '/logout' => 'sessions#destroy'
    end
  end

  match '*path', via: [:options], to:  lambda {|_| [204, {'Content-Type' => 'text/plain'}, []]}

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list

  validates :name, length: {minimum: 5}
end

app/controllers/api/v1/items_controller.rb
class Api::V1::ItemsController < ApiController
  before_action :find_list
  before_action :find_item, only: [:show, :update, :destroy]

  # GET /api/v1/lists/:list_id/items
  def index
    @items = @list.items
    render json: @items
  end

  # GET /api/v1/lists/:list_id/items/:id
  def show
    render json: @item
  end

  # POST /api/v1/lists/:list_id/items
  def create
    @item = @list.items.build(item_params)

    if @item.save
      render json: @item
    else
      render json: @item.errors, status: :unprocessable_entity # status code 422
    end
  end

  # PUT /api/v1/lists/:list_id/items/:id
  def update
    if @item.update(item_params)
      render json: @item
    else
      render json: @item.errors, status: :unprocessable_entity # status code 422
    end
  end

  # DELETE /api/v1/lists/:list_id/items/:id
  def destroy
    @item.destroy
    render json: { success: true }
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end

  def find_list
    @list = List.find(params[:list_id])
  end

  def find_item
    @item = @list.items.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_list

  # GET /lists/:list_id/items/:id
  def show
    @item = @list.items.find(params[:id])
  end

  # GET /lists/:list_id/items/new
  def new
    @item = Item.new
  end

  # POST /lists/:list_id/items
  def create
    @item = @list.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @list }
        format.js {}
      else
        format.html { render "new" }
        format.js {}
      end
    end
  end

  # GET /lists/:list_id/items/:id/edit
  def edit
    @item = @list.items.find(params[:id])
  end

  # PATCH/PUT /lists/:list_id/items/:id
  def update
    @item = @list.items.find(params[:id])
    if @item.update(item_params)
      redirect_to @list
    else
      render 'edit'
    end
  end

  # DELETE /lists/:list_id/items/:id
  def destroy
    @item = @list.items.find(params[:id])
    @item.destroy

    redirect_to @list
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end

  def find_list
    @list = List.find(params[:list_id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_create_form.html.erb
<% if item.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(item.errors.count, "error") %> prohibited this article from being saved.</h2>

  <ul>
    <% item.errors.full_messages.each do |error_message| %>
    <li><%= error_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<!-- Modified the form url parameter so that it supports POST to different controller -->
<%= form_for item, url: list_items_path(list), html: { method: :post }, remote: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, id: "item-name-input" %>

  <%= form.submit "Create Item" %>
<% end %>

app/views/items/_item.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="item">
      <ul class="item-right">
        <li><%= button_to "Show", list_item_path(@list.id, item.id), method: "get"%></li>
        <li><%= button_to "Edit", edit_list_item_path(@list.id, item.id), method: "get"%></li>
        <li><%= button_to "Delete", list_item_path(@list.id, item.id), method: "delete"%></li>
      </ul>

      <div class="item-left">
        <%= item.id %>
        <%= item.name %>
      </div>

    </div>
  </div>
</div>

app/views/items/_item_errors.html.erb
<div id="item_error_explanation">
  <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved.</h2>

  <ul>
    <% item.errors.full_messages.each do |error_message| %>
    <li><%= error_message %></li>
    <% end %>
  </ul>
</div>

app/views/items/_update_form.html.erb
<% if item.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(item.errors.count, "error") %> prohibited this article from being saved.</h2>

  <ul>
    <% item.errors.full_messages.each do |error_message| %>
    <li><%= error_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<!-- Modified the form url parameter so that it supports PUT to different controller -->
<%= form_for item, url: list_item_path(list, item), html: { method: :put } do |form| %>
  <%= form.label :name%>
  <%= form.text_field :name%>

  <%= form.submit "Update Item" %>
<% end %>

app/views/items/create.js.erb
<% if @item.errors.any? %>
  $("#item-errors").html("<%= escape_javascript(render partial: 'item_errors', locals: {list: @list, item: @item}) %>");
<% else%>
  $("#item-errors").html("");
  var itemElement = $(".item");
  if (itemElement.length >= 5) {
    $(".item").last().remove();
  }
  if (itemElement.length >= 5 && isLastPage()) {
    addNewPage(window.location.pathname);
  }
  $("#items").prepend("<%= escape_javascript(render @item) %>");
  $("#create-item-modal").modal("hide");
  $("#item-name-input").val("");
<% end %>

app/views/items/edit.html.erb
<h1>Edit the item: <%= @item.name%></h1>

<%= render partial: "update_form", locals: {list: @list, item: @item}%>

app/views/items/new.html.erb
<h1>Create a new item for <%= @list.name%></h1>

<%= render partial: "form", locals: {list: @list, item: @item, action: "create"}%>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<%= button_to "Edit", edit_list_item_path(@list.id, @item.id), method: "get"%>
<%= button_to "Delete", list_item_path(@list.id, @item.id), method: "delete"%>